import React from "react";

const TermsPage = () => {

  return (
    <div className="bg-[#F7F9FB] rounded-[20px] md:pt-[160px] pt-20 pb-5 md:pb-24 px-5 md:px-12 flex flex-col items-center mb-8">
      <div className="text-center mb-5 md:mb-[34px]">
        <h1 className="mb-3 text-[#212427] text-[40px] md:text-[52px] leading-[48px] md:leading-[60px] font-medium">
          bottest.ai Terms of Service
        </h1>
        <p className="mb-5 md:mb-[34px] text-[#616A73] md:text-base text-sm">
          Our Terms of Service was last updated on May 21, 2024.
        </p>
      </div>
      <ol className="px-24 list-decimal">
        <p >
          These Terms of Service (this <b>“Agreement”</b>) are entered into by and between Bot Test Inc., a Delaware corporation (<b>“bottest.ai”</b>), and the entity or person accessing or using the bottest.ai Platform (<b>“Customer”</b> or <b>“you”</b>). This Agreement consists of the terms and conditions set forth below and any Order Forms that reference this Agreement. If you are accessing or using the bottest.ai Platform on behalf of your company, you represent that you are authorized to accept this Agreement on behalf of your company, and all references to “you” reference your company.
          < br />< br />
          Please note that bottest.ai may modify the terms and conditions of this Agreement in accordance with Section 8.4 (Amendment; Waiver).
          < br />< br />
          BY INDICATING YOUR ACCEPTANCE OF THIS AGREEMENT OR ACCESSING OR USING THE BOTTEST.AI PLATFORM, YOU ARE AGREEING TO BE BOUND BY ALL TERMS, CONDITIONS AND NOTICES CONTAINED OR REFERENCED IN THIS AGREEMENT. IF YOU DO NOT AGREE TO THIS AGREEMENT, PLEASE DO NOT USE THE BOTTEST.AI PLATFORM. FOR CLARITY, EACH PARTY EXPRESSLY AGREES THAT THIS AGREEMENT IS LEGALLY BINDING UPON IT.
        </p>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">Definitions</li>
        <p>
          The following terms, when used in this Agreement will have the following meanings:
          < br />< br />
          <b>“Affiliate”</b> means any entity that directly or indirectly controls, is controlled by, or is under common control with another entity, so long as such control exists. For the purposes of this definition, <b>“Control”</b> means beneficial ownership of 50% or more of the voting power or equity in an entity.
          < br />< br />
          <b>"Confidential Information"</b> means any information or data disclosed by either party that is marked or otherwise designated as confidential or proprietary or that should otherwise be reasonably understood to be confidential in light of the nature of the information and the circumstances surrounding disclosure. However, “Confidential Information” will not include any information which (a) is in the public domain through no fault of receiving party;(b) was properly known to receiving party, without restriction, prior to disclosure by the disclosing party; ( c) was properly disclosed to receiving party, without restriction, by another person with the legal authority to do so; or(d) is independently developed by the receiving party without use of or reference to the disclosing party’s Confidential Information.
          < br />< br />
          <b>"Documentation"</b> means the printed and digital instructions, on-line help files, technical documentation and user manuals made available by bottest.ai for the bottest.ai Platform.
          < br />< br />
          <b>"bottest.ai Distributed Code"</b> means any software code provided by bottest.ai to Customer for use in connection with the bottest.ai Platform.
          < br />< br />
          <b>"bottest.ai Platform</b> means bottest.ai’s application development platform for monitoring, testing, and debugging chatbot applications, which may be provided both as a cloud offering or on-premise (including local) deployment.
          < br />< br />
          <b>"Order Form</b> means any bottest.ai online sign-up, order form, statement of work, service addendum or other sign-up flow that references this Agreement.
          < br />< br />
          <b>"Special Data"</b> means data or information considered to be sensitive or otherwise subject to specific protections under applicable laws beyond any requirements that apply to “personal information” or“personal data” generally, such as for illustrative purposes, information that is regulated by the Health Information Portability and Accountability Act, the Payment Card Industry Data Security Standard, the Gramm-Leach-Bliley Act, and other U.S. federal, state or foreign laws applying specific security standards.
          < br />< br />
          <b>"Third-Party Product"</b> means any applications, integrations, software, code, online services, systems, or other products not developed by bottest.ai.
        </p>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">bottest.ai Platform</li>
        <ol className="list-decimal">
          <li>Account Registration. Customer may need to register for a bottest.ai account in order to use the bottest.ai Platform. Account information must be accurate, current, and complete. Customer agrees to keep this information up-to-date so that bottest.ai may send notices, statements, and other information by email or through Customer’s account. Customer must ensure that any user IDs, passwords, and other access credentials for the bottest.ai Platform are kept strictly confidential and not shared with any unauthorized person.</li>
          <br />
          <li>Eligibility. To access or use the bottest.ai Platform, Customer must have the requisite power and authority to enter into this Agreement. In addition, Customer may not access or use the bottest.ai Platform if (i) Customer is a competitor of bottest.ai; (ii) bottest.ai has previously terminated Customer’s access to the bottest.ai Platform for violation of this Agreement; or (iii) if Customer is an individual under the age of 18 (or the age of majority in Customer’s jurisdiction). If bottest.ai has reason to believe thatCustomer is in violation of the foregoing, bottest.ai reserves the right to terminate access to Customer’s bottest.ai account.</li>
          <br />
          <li>License to bottest.ai Platform.Subject to the terms and conditions of this Agreement, bottest.ai hereby grants Customer a non-exclusive, non-transferrable, non-sublicensable right to access and use the bottest.ai Platform set forth in the corresponding Order Form for its internal business purposes. To the extent bottest.ai has provided Customer with any bottest.ai Distributed Code, rights granted in this Section further include the right to install and run the relevant bottest.ai Distributed Code in connection with Customer’s use of the bottest.ai Platform.</li>
          <br />
          <li>Free Access Subscriptions. bottest.ai may provide Customer with the bottest.ai Platform for free or on a trial basis (“Free Access Subscriptions”). bottest.ai makes no promises that any Free Access Subscriptions will be made available under the same commercial or other terms. bottest.ai may terminate Customer’s right to use any Free Access Subscriptions at any time in bottest.ai’s sole discretion without liability; provided that bottest.ai will use commercially reasonable efforts to provide Customer fifteen (15) days’ written notice (email to suffice) if bottest.ai elects to institute a fee for Customer’s access to the bottest.ai Platform or terminate Customer’s Free Access Subscription without cause. Any Free Access Subscriptions are provided by bottest.ai “AS-IS” and without any representations, warranties, performance or data security guarantees or support obligations.</li>
          <br />
          <li>License Keys. Certain portions of the bottest.ai Platform or bottest.ai Distributed Code may require an authorized license key from bottest.ai. The license key may impose limits on the use of the bottest.ai Platform or bottest.ai Distributed Code, such as the license term or number of authorized users. Customer is solely responsible for maintaining active license key(s) to ensure continued access and use of the corresponding features of the bottest.ai Platform or bottest.ai Distributed Code, and bottest.ai reserves the right to suspend access in the event Customer’s license key(s) are invalid or expired.</li>
          <br />
          <li>Customer Limitations. Customer will not directly or indirectly: (a) reverse engineer, decompile, disassemble, modify, create derivative works of or otherwise create, attempt to create or derive, or permit or assist any third party to create or derive, the source code underlying the bottest.ai Platform; (b) attempt to probe, scan or test the vulnerability of the bottest.ai Platform, breach the security or authentication measures of the bottest.ai Platform without proper authorization or willfully render any part of the bottest.ai Platform unusable; ( c) use or access the bottest.ai Platform to develop a product or service that is competitive with bottest.ai products or services or engage in competitive analysis or benchmarking; (d) transfer, distribute, resell, lease, license, or assign the bottest.ai Platform or otherwise offer the bottest.ai Platform on a standalone basis; (e) upload any information that constitutes Special Data; (f) use the bottest.ai Platform for applications in which the failure of the bottest.ai Platform could lead directly to death, personal injury, or severe physical or environmental damage (<b>“High Risk Activities”</b>) or (g) otherwise use the bottest.ai Platform in violation of applicable law (including any export law) or outside the scope expressly permitted hereunder and in the applicable Order Form (collectively, the <b>“License Restrictions”</b>).</li>
          <br />
          <li>Customer Responsibilities. Customer will (i) be responsible for all use of the bottest.ai Platform under its account, (ii) use commercially reasonable efforts to prevent unauthorized access to or use of the bottest.ai Platform and notify bottest.ai promptly of any such unauthorized access or use or any other known or suspected breach of security or misuse of the bottest.ai Platform; (iii) be responsible for obtaining and maintaining any equipment, software and ancillary services needed to connect to, access or otherwise use the bottest.ai Platform, including as set forth in the Documentation; and (iv) obtaining all rights, consents, and permissions necessary for bottest.ai to process any Customer Data (as defined below) in connection with the activities contemplated under this Agreement. Customer will be solely responsible for its failure to maintain such equipment, software and services, and bottest.ai will have no liability for such failure (including under any service level agreement).</li>
          <br />
          <li>Third-Party Products. If Customer uses Third-Party Products in connection with the bottest.ai Platform (such as through integrations made available by bottest.ai), Customer agrees and acknowledges that bottest.ai does not warrant or support Third-Party Products and disclaims all responsibility and liability for these items and their use in connection with the bottest.ai Platform.</li>
          <br />
          <li>Affiliates. Any Affiliate of Customer will have the right to enter into an Order Form executed by such Affiliate and bottest.ai and this Agreement will apply to each such Order Form as if such Affiliate were a signatory to this Agreement. With respect to such Order Forms, such Affiliate becomes a party to this Agreement and references to Customer in this Agreement are deemed to be references to such Affiliate. Each Order Form is a separate obligation of the Customer entity that executes such Order Form, and no other Customer entity has any liability or obligation under such Order Form.</li>
        </ol>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">Fees</li>
        <ol className="list-decimal">
          <li>Fees. To the extent any portions of the bottest.ai Platform (including related support or other ancillary services) are made available for a fee, Customer will pay bottest.ai the amounts as set forth in the Order Form. Except as otherwise specified herein or in any applicable Order Form, (a) fees are quoted and payable in United States dollars and (b) payment obligations are non-cancelable and non-pro-ratable for partial months, and fees paid are non-refundable.</li>
          <br />
          <li>Credit Card Payment Terms. If Customer elects to pay via credit card, then Customer is responsible for either (a) enabling auto-recharge on Customer’s payment instrument or (b) ensuring that Customer’s payment instrument has a sufficient positive balance to cover all fees due. If, for any reason, Customer has a negative balance on its payment account, then bottest.ai reserves the right to suspend access to the paid services until all fees are paid in full. Customer hereby authorizes bottest.ai to charge Customer’s designated credit card account (or other means of payment) for the fees set forth in the corresponding Order Form.</li>
          <br />
          <li>Invoicing Payment Terms. If Customer elects to receive invoices and bottest.ai approves Customer for the same, then invoices will be sent to via email in accordance with the Order Form. Except as otherwise set forth in an Order Form, Customer will make all of the undisputed fees hereunder within thirty (30) days of the date of the invoice.</li>
          <br />
          <li>Suspension; Late Payment. bottest.ai may suspend access to the bottest.ai Service immediately upon notice if Customer fails to pay any amounts hereunder at thirty (30) days past the applicable due date. If bottest.ai has not received payment within thirty (30) days after the applicable due date, interest will accrue on past due amounts at the rate of one percent (1%) per month, but in no event greater than the highest rate of interest allowed by law, calculated from the date such amount was due until the date that payment is received by bottest.ai. In addition, Customer will be liable to bottest.ai for all costs incurred by bottest.ai in its collection of any amounts owed by Customer, which are not paid when due, including, without limitation, collection agency fees or reasonable attorneys’ fees and expenses.</li>
          <br />
          <li>Taxes. All amounts payable hereunder are exclusive of any sales, use and other taxes or duties, however designated (collectively <b>“Taxes”</b>). Customer will be solely responsible for payment of all Taxes, except for those taxes based on the income of bottest.ai. Customer will not withhold any taxes from any amounts due to bottest.ai.</li>
        </ol>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">Proprietary Rights and Confidentiality</li>
        <ol className="list-decimal">
          <li>Customer Data. Customer shall retain all right, title and interest to all data and information uploaded or provided by Customer to bottest.ai in connection with its use of the bottest.ai Platform (“Customer Data”). Customer warrants that it has all rights necessary to provide any information, data or other materials that it provides hereunder, and to permit bottest.ai to use the same as contemplated hereunder. bottest.ai agrees that it will not use Customer Data to develop or improve its products and services.</li>
          <br />
          <li>Data Security. bottest.ai will maintain a security program materially in accordance with industry standards that is designed to (i) ensure the security and integrity of Customer Data (ii) protect against threats or hazards to the security or integrity of Customer Data; and (iii) prevent unauthorized access to Customer Data.</li>
          <br />
          <li>Proprietary Rights. As between the parties, bottest.ai exclusively owns all right, title and interest in and to the bottest.ai Platform, bottest.ai Distributed Code, System Data and bottest.ai ‘s Confidential Information (<b>“bottest.ai Materials”</b>). Customer exclusively owns all right, title and interest in and to the applications it develops using the bottest.ai Platform (excluding any bottest.ai Materials). <b>“System Data”</b> means data collected by bottest.ai regarding the bottest.ai Platform that may be used to generate logs, statistics or reports regarding the performance, availability, usage, integrity or security of the bottest.ai Platform.</li>
          <br />
          <li>Feedback. Customer may from time to time provide bottest.ai suggestions or comments for enhancements or improvements, new features or functionality or other feedback (<b>“Feedback”</b>) with respect to the bottest.ai Platform. bottest.ai will have full discretion to determine whether or not to proceed with the development of any requested enhancements, new features or functionality. bottest.ai will have the full, unencumbered right, without any obligation to compensate or reimburse Customer, to use, incorporate and otherwise fully exercise and exploit any such Feedback in connection with its products and services.</li>
          <br />
          <li>Confidentiality. Each party agrees that it will use the Confidential Information of the other party solely in accordance with the provisions of this Agreement and it will not disclose the same directly or indirectly, to any third party without the other party’s prior written consent, except as otherwise permitted hereunder. However, either party may disclose Confidential Information (a) to its employees, officers, directors, attorneys, auditors, financial advisors and other representatives who have a need to know and are legally bound to keep such information confidential by confidentiality obligations consistent with those of this Agreement; and (b) as required by law (in which case the receiving party will provide the disclosing party with prior written notification thereof, will provide the disclosing party with the opportunity to contest such disclosure, and will use its reasonable efforts to minimize such disclosure to the extent permitted by applicable law). Neither party will disclose the terms of this Agreement to any third party, except that either party may confidentially disclose such terms to actual or potential lenders, investors or acquirers. Each party agrees to exercise due care in protecting the Confidential Information from unauthorized use and disclosure. In the event of actual or threatened breach of the provisions of this Section or the License Restrictions, the non-breaching party will be entitled to seek immediate injunctive and other equitable relief, without waiving any other rights or remedies available to it. Each party will promptly notify the other in writing if it becomes aware of any violations of the confidentiality obligations set forth in this Agreement.</li>
        </ol>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">Disclaimers</li>
        <ol className="list-decimal">
          <li>EXCEPT AS EXPRESSLY SET FORTH HEREIN, BOTTEST.AI DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE, INCLUDING USE IN CONNECTION WITH ANY HIGH RISK ACTIVITIES. BOTTEST.AI DOES NOT REPRESENT OR WARRANT THAT THE BOTTEST.AI PLATFORM WILL BE ERROR-FREE, AND BOTTEST.AI EXPRESSLY DISCLAIMS ANY WARRANTY AS TO THE ACCURACY OR COMPLETENESS OF ANY INFORMATION OR DATA ACCESSED OR USED IN CONNECTION WITH THE BOTTEST.AI PLATFORM. BOTTEST.AI IS NOT RESPONSIBLE OR LIABLE FOR ANY PRODUCTS OR SERVICES NOT PROVIDED BY BOTTEST.AI (INCLUDING ANY THIRD-PARTY PRODUCTS), AND DOES NOT GUARANTEE THE CONTINUED AVAILABILITY THEREOF OR ANY INTEGRATION THEREWITH, AND MAY CEASE MAKING ANY SUCH INTEGRATION AVAILABLE IN ITS SOLE DISCRETION.</li>
        </ol>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">Limitation of Liability; Indemnification</li>
        <ol className="list-decimal">
          <li>Limitation of Liability. UNDER NO LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, WILL (A) BOTTEST.AI BE LIABLE UNDER THIS AGREEMENT FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES OF ANY CHARACTER, INCLUDING DAMAGES FOR LOSS OF GOODWILL, LOST PROFITS, LOST SALES OR BUSINESS, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, LOST CONTENT OR DATA, EVEN IF A REPRESENTATIVE OF BOTTEST.AI HAS BEEN ADVISED, KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, OR (B) BOTTEST.AI BE LIABLE FOR ANY AGGREGATE DAMAGES, COSTS, OR LIABILITIES IN EXCESS OF THE AMOUNTS PAID BY CUSTOMER UNDER THE APPLICABLE ORDER FORM DURING THE TWELVE (12) MONTHS PRECEDING THE INCIDENT OR CLAIM, OR ONE HUNDRED DOLLARS ($100.00), WHICHEVER IS GREATER.</li>
          <br />
          <li>Indemnification. Customer agrees to defend, indemnify, and hold harmless bottest.ai from and against any claims, actions or demands, including, without limitation, all related liabilities, damages, costs, expenses, and reasonable legal and accounting fees, arising or resulting from Customer’s breach of the Agreement or Customer’s access to, use or misuse of the bottest.ai Platform. bottest.ai shall provide notice to Customer of any such claim, suit, or proceeding. bottest.ai reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this Section. In such case, Customer agrees to cooperate with any reasonable requests assisting bottest.ai defense of such matter.</li>
        </ol>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">Term; Termination</li>
        <ol className="list-decimal">
          <li>Paid Subscription or Services. If Customer has purchased any products, support, or services from bottest.ai pursuant to an Order Form, this Agreement will be in effect for the term set forth in the Order Form. Unless otherwise agreed upon by the parties in writing, Customer’s Order Form automatically renew for additional, successive renewal terms of equal length unless either party provides the other party with written notice of non-renewal at least (30) days before the end of the then-current renewal term. In addition, each party may each terminate this Agreement if the other party fails to cure any material breach of this Agreement (including a failure to pay undisputed fees) within thirty (30) days after written notice detailing the breach.</li>
          <br />
          <li>Free Access Subscriptions. If Customer is accessing the bottest.ai Platform via a Free Access Subscription and has not otherwise agreed to purchase any other support or services, Customer may terminate this Agreement upon written notice to bottest.ai, and bottest.ai may terminate this Agreement upon thirty (30) days’ written notice to Customer(or immediately if Customer is in material breach of this Agreement). In addition, bottest.ai reserves the right to delete Customer Data stored by bottest.ai in the event Customer’s bottest.ai account has been inactive for at least one (1) year.</li>
          <br />
          <li>Effect of Termination; Survival. Upon termination of this Agreement all rights and obligations will immediately terminate except that any terms or conditions that by their nature should survive such termination will survive, including the License Restrictions and terms and conditions relating to proprietary rights and confidentiality, disclaimers, indemnification, limitations of liability and termination and the general provisions below. To the extent bottest.ai has provided Customer with any bottest.ai Distributed Code, Customer must stop using any installed bottest.ai Distributed Code within 60 days of termination this Agreement and must destroy any copies of bottest.ai Confidential Information within Customer’s control.</li>
        </ol>
        <li className="mt-14 mb-6 text-[#212427] text-[20px] md:text-[26px] leading-[24px] md:leading-[30px] font-medium">General</li>
        <ol className="list-decimal">
          <li>Export Compliance. Each party will comply with the export laws and regulations of the United States, European Union and other applicable jurisdictions in providing and using the bottest.ai Platform.</li>
          <br />
          <li>Publicity. Customer agrees that bottest.ai may refer to Customer’s name, logo, and trademarks in bottest.ai marketing materials and website; however, bottest.ai will not use Customer’s name or trademarks in any other publicity (e.g., press releases, customer references and case studies) without Customer’s prior written consent (which may be by email) not to be unreasonably delayed</li>
          <br />
          <li>Assignment; Delegation. Neither party hereto may assign or otherwise transfer this Agreement, in whole or in part, without the other party’s prior written consent, except that either party may assign this Agreement without consent to a successor to all or substantially all of its assets or business related to this Agreement. Any attempted assignment, delegation, or transfer by either party in violation hereof will be null and void. Subject to the foregoing, this Agreement will be binding on the parties and their successors and assigns.</li>
          <br />
          <li>Amendment; Waiver. bottest.ai reserves the right in its sole discretion and at any time and for any reason to modify this Agreement. Any modifications to this Agreement shall become effective upon the date of posting. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. Any such waiver will be only to the specific provision and under the specific circumstances for which it was given, and will not apply with respect to any repeated or continued violation of the same provision or any other provision. Failure or delay by either party to enforce any provision of this Agreement will not be deemed a waiver of future enforcement of that or any other provision.</li>
          <br />
          <li>Relationship. Nothing contained herein will in any way constitute any association, partnership, agency, employment or joint venture between the parties hereto, or be construed to evidence the intention of the parties to establish any such relationship. Neither party will have the authority to obligate or bind the other in any manner, and nothing herein contained will give rise or is intended to give rise to any rights of any kind to any third parties.</li>
          <br />
          <li>Unenforceability. If a court of competent jurisdiction determines that any provision of this Agreement is invalid, illegal, or otherwise unenforceable, such provision will be enforced as nearly as possible in accordance with the stated intention of the parties, while the remainder of this Agreement will remain in full force and effect and bind the parties according to its terms.</li>
          <br />
          <li>Governing Law. This Agreement will be governed by the laws of the State of Delaware, exclusive of its rules governing choice of law and conflict of laws. This Agreement will not be governed by the United Nations Convention on Contracts for the International Sale of Goods.</li>
          <br />
          <li>Notices. Any notice required or permitted to be given hereunder will be given in writing by personal delivery, certified mail, return receipt requested, or by overnight delivery. Notices to the Customer may be sent to the address listed on the Customer’s applicable Order Form or email address provided by Customer when Customer creates its bottest.ai Platform account. Notices to bottest.ai must be sent to the following: Bot Test Inc., 1214 Stanyan Street., San Francisco, CA 94117.</li>
          <br />
          <li>Entire Agreement. This Agreement comprises the entire agreement between Customer and bottest.ai with respect to its subject matter, and supersedes all prior and contemporaneous proposals, statements, sales materials or presentations and agreements (oral and written). No oral or written information or advice given by bottest.ai, its agents or employees will create a warranty or in any way increase the scope of the warranties in this Agreement.</li>
          <br />
          <li>Force Majeure. Neither party will be deemed in breach hereunder for any cessation, interruption or delay in the performance of its obligations due to causes beyond its reasonable control, including earthquake, flood, or other natural disaster, act of God, labor controversy, civil disturbance, terrorism, war (whether or not officially declared), cyber-attacks (e.g., denial of service attacks), or the inability to obtain sufficient supplies, transportation, or other essential commodity or service required in the conduct of its business, or any change in or the adoption of any law, regulation, judgment or decree.</li>
          <br />
          <li>Government Terms. bottest.ai provides the bottest.ai Platform, including related software and technology, for ultimate federal government end use solely in accordance with the terms of this Agreement. If Customer is an agency, department, or other entity of any government, the use, duplication, reproduction, release, modification, disclosure, or transfer of the bottest.ai Platform, or any related documentation of any kind, including technical data, software, and manuals, is restricted by the terms of this Agreement. All other use is prohibited and no rights than those provided in this Agreement are conferred. The bottest.ai Platform was developed fully at private expense.</li>
        </ol>
      </ol>
    </div>
  );
};

export default TermsPage;
